version: '2.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  web:
    build: .
    image: web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/image-ms
    ports:
      - "3000:3000"
    depends_on:
      - db
