version: '2.1'
services:
  db:
    image: postgres
    ports:
      - "5435:5435"
    volumes:
      - /var/lib/postgresql/data
  web:
    build: .
    image: web
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    volumes:
      - .:/image-ms
    ports:
      - "3002:3002"
    depends_on:
      - db
